### ISSUE TITLE
Use with self-hosted LLM or without OpenAI?

### ISSUE THREAD

**Issue by sunjam** [gitayam/matrix-to-discourse#1]
Hi, wondering if it is possible to use this without OpenAI.
Either without or with a self-hosted, open source LLM.

Thanks!

**Comment by gitayam** [comment]
Yea actually I have some branches where it did just that

I'll work on giving the option within the main branch. Gpt is used to create titles for the pos

- [x] Create local llm option
- [x] Create handling for title as sub command when GPT should not create a title
- [x] Create option to gracefully work without GPT

**Comment by gitayam** [comment]
@sunjam i've started working on this in this branch https://github.com/gitayam/matrix-to-discourse/tree/local-llm-option-added

**Comment by gitayam** [comment]
@sunjam I've completed all the updates , appreciate you bringing it up actually . 

https://github.com/gitayam/matrix-to-discourse/releases/tag/v1.1

**Comment by sunjam** [comment]
Thank you.  Started a thread on the meta discourse forum, in case you would like to engage with the Discourse crew more directly. ❤️ 

https://meta.discourse.org/t/github-gitayam-matrix-to-discourse-a-maubot-plugin-that-allows-users-to-post-messages/331676
